version: "3.9"
services:
  jumserver:
    image: jumpserver/jumpserver:latest
    container_name: jumserver
    restart: unless-stopped
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jumserver.rule=Host(`ggllp.jumserver.local`)"
      - "traefik.http.services.jumserver.loadbalancer.server.port=80"

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
