version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: mattermost_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - default

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost_app
    restart: unless-stopped
    ports:
      - "8065:8065"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`ggllp.mattermost.local`)"
      - "traefik.http.routers.mattermost.entrypoints=web"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
      # - "traefik.http.routers.mattermost.tls=true"
      # - "traefik.http.routers.mattermost.tls.certresolver=myresolver"
    networks:
      - default
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost_user:mattermost_password@postgres/mattermost?sslmode=disable
    volumes:
      - mattermost_data:/mattermost/data
    depends_on:
      - postgres


volumes:
  postgres_data:
  mattermost_data:


networks:
  default:
    external: true
    name: ${NETWORK_NAME}
